network:
  wan1_interface: enp3s0
  wan2_interface: enx00e04c680270
  lan_interface: enp4s0
  bridge_name: br0
  lan_cidr: 192.168.100.1/24
  dhcp_start: 192.168.100.50
  dhcp_end: 192.168.100.200
  dhcp_lease: 12h
  dns_servers:
    - 1.1.1.1
    - 8.8.8.8

manual:
  selected_wan: wan1
